#+author: conao
#+date: <2019-06-22 Sat>

[[https://github.com/conao3/docker-imagick][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/docker-imagick.png]]
[[https://github.com/conao3/docker-imagick/blob/master/LICENSE][https://img.shields.io/github/license/conao3/docker-imagick.svg?style=flat-square]]
[[https://github.com/conao3/docker-imagick/releases][https://img.shields.io/github/tag/conao3/docker-imagick.svg?style=flat-square]]
[[https://travis-ci.org/conao3/docker-imagick][https://img.shields.io/travis/conao3/docker-imagick/master.svg?style=flat-square]]
[[https://app.codacy.com/project/conao3/docker-imagick/dashboard][https://img.shields.io/codacy/grade/83ace41d79694519ab76fadc9ae89fbe.svg?logo=codacy&style=flat-square]]
[[https://www.patreon.com/conao3][https://img.shields.io/badge/patreon-become%20a%20patron-orange.svg?logo=patreon&style=flat-square]]
[[https://twitter.com/conao_3][https://img.shields.io/badge/twitter-@conao__3-blue.svg?logo=twitter&style=flat-square]]
[[https://conao3-support.slack.com/join/shared_invite/enQtNjUzMDMxODcyMjE1LWUwMjhiNTU3Yjk3ODIwNzAxMTgwOTkxNmJiN2M4OTZkMWY0NjI4ZTg4MTVlNzcwNDY2ZjVjYmRiZmJjZDU4MDE][https://img.shields.io/badge/chat-on_slack-blue.svg?logo=slack&style=flat-square]]

* Table of Contents
- [[#description][Description]]
- [[#install][Install]]
- [[#usage][Usage]]
- [[#information][Information]]
  - [[#donation][Donation]]
  - [[#community][Community]]
  - [[#contribution][Contribution]]
  - [[#license][License]]
  - [[#author][Author]]
  - [[#contributors][Contributors]]

* Description
~docker-imagick~ is standalone [[https://github.com/ImageMagick/ImageMagick][ImageMagick]].

* Install
Depend Docker.

#+begin_src bash
  brew install docker
  brew cask install docker

  # docker start-up test
  docker version
#+end_src

* Usage
Run ~docker-imagick~ like as below.

#+begin_src bash
  $ docker run -it conao3/imagick                                                                                                                                                                      622ms  土  6/22 12:21:01 2019
  Version: ImageMagick 7.0.8-44 Q16 x86_64 2019-05-06 https://imagemagick.org
  Copyright: © 1999-2019 ImageMagick Studio LLC
  License: https://imagemagick.org/script/license.php
  Features: Cipher DPC HDRI Modules
  Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jpeg lcms ltdl pangocairo png ps rsvg tiff webp x xml zlib
#+end_src

Or, alias it.
# #+begin_src bash
#   $ alias jq1.6='docker container run -i --rm conao3/jq:1.6'
#   $ echo '{"version":100}' | jq1.6 '.version'
#   100
# #+end_src

* Information
** Donation
I love OSS and I am dreaming of working on it as *full-time* job.

*With your support*, I will be able to spend more time at OSS!

[[https://www.patreon.com/conao3][https://c5.patreon.com/external/logo/become_a_patron_button.png]]

** Community
All feedback and suggestions are welcome!

You can use github issues, but you can also use [[https://conao3-support.slack.com/join/shared_invite/enQtNjUzMDMxODcyMjE1LWUwMjhiNTU3Yjk3ODIwNzAxMTgwOTkxNmJiN2M4OTZkMWY0NjI4ZTg4MTVlNzcwNDY2ZjVjYmRiZmJjZDU4MDE][Slack]]
if you want a more casual conversation.

** Contribution
Feel free to send PR!

** License
#+begin_example
  Affero General Public License Version 3 (AGPLv3)
  Copyright (c) Naoya Yamashita - https://conao3.com
  https://github.com/conao3/docker-imagick/blob/master/LICENSE
#+end_example

** Author
- Naoya Yamashita ([[https://github.com/conao3][conao3]])

** Contributors
- Not yet... Now send PR and add your name!!
